# Generated by Django 5.2.8 on 2025-11-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('js_file_path', models.CharField(help_text='e.g., js/doc_templates/legal_notice.js', max_length=255)),
                ('icon_class', models.CharField(blank=True, default='fas fa-file-alt', max_length=100)),
            ],
        ),
    ]
